#!/usr/bin/env python3
#
# Draw call flow graph from a database generated by mk-dwarf-db.py.
#
# Usage: draw-callflow.py [-f <+caller|-callee>] [-n <levels>]
#                         [-x <exclude-symbol>]
#                         [-o <output-file>] <database>
#
# Options:
#   -f <+caller|-callee>  Follow caller to functions called by the caller, or
#                         follow callee to functions calling the callee.
#   -n <levels>           Number of levels to follow.
#   -x <exclude-symbol>   Exclude the specified symbol. Stop following the
#                         symbol.
#   -o <output-file>      Output file name. If not specified, output to stdout.
#
# You can specify multiple -f options to follow multiple call paths.
#
# Example:
#   draw-callflow.py -f +caller -f -callee -n 2 -o callflow.dot my-database
#
# This will draw a call flow graph with two levels of callers and two levels of
# callees.
#
import sys
import optparse
import sqlite3

#
# Database schema:
#
#    CREATE TABLE symbols (
#        id integer primary key asc,
#        name text unique
#    );
#
#    CREATE TABLE calls (
#        caller integer,
#        callee integer
#    );
#

class CallflowNode:
    def __init__(self, name, tree):
        self.name = name
        self.tree = tree
        self.children = []
        pass

    def add_non_existing_child(self, child):
        if child.name in self.tree.symbols:
            return False
        self.children.append(child)
        self.tree.symbols[child.name] = child
        return True
    pass

class CallflowTree:
    def __init__(self, name, to_callee):
        self.root = CallflowNode(name, self)
        self.symbols = {name: self.root}
        self.to_callee = to_callee
        pass

    def draw(self, out):
        if self.to_callee:
            self.draw_to_callee(out)
        else:
            self.draw_to_caller(out)
            pass
        pass

    def draw_to_callee(self, out):
        tasks = [self.root]
        while tasks:
            node = tasks.pop()
            for child in node.children:
                out.write('"%s" -> "%s";\n' % (node.name, child.name))
                tasks.append(child)
                pass
            pass
        pass

    def draw_to_caller(self, out):
        tasks = [self.root]
        while tasks:
            node = tasks.pop()
            for child in node.children:
                out.write('"%s" -> "%s";\n' % (child.name, node.name))
                tasks.append(child)
                pass
            pass
        pass
    pass

def create_callflow_tree(conn, name, levels, exclude, to_callee):
    tree = CallflowTree(name, to_callee)
    tasks = [(name, levels)]
    while tasks:
        (name, level) = tasks.pop()
        if level == 0:
            continue
        id = conn.execute("SELECT id FROM symbols WHERE name = ?",
                          (name,)).fetchone()[0]
        if to_callee:
            query = "SELECT callee FROM calls WHERE caller = ?"
        else:
            query = "SELECT caller FROM calls WHERE callee = ?"
            pass
        for row in conn.execute(query, (id,)):
            callee_or_caller = row[0]
            child_name = \
                conn.execute("SELECT name FROM symbols WHERE id = ?",
                             (callee_or_caller,)).fetchone()[0]
            node = CallflowNode(child_name, tree)
            if tree.symbols[name].add_non_existing_child(node) \
               and child_name not in exclude:
                tasks.append((child_name, level - 1))
                pass
            pass
        pass
    return tree

def usage():
    print("Usage: %s [-f <+caller|-callee>] [-n <levels>]" % sys.argv[0])
    print("          [-x <exclude-symbol>] [-o <output-file>] <database>")
    print("        [-o <output-file>] <database>")
    sys.exit(1)
    pass

def main():
    parser = optparse.OptionParser()
    parser.add_option("-f", "--follow", dest="follow", action="append",
                      help="Follow caller to functions called by the caller, or "
                      "follow callee to functions calling the callee.")
    parser.add_option("-n", "--levels", dest="levels", type="int",
                      help="Number of levels to follow.")
    parser.add_option("-x", "--exclude", dest="exclude", action="append",
                        help="Exclude the specified symbol. Stop following the "
                        "symbol.")
    parser.add_option("-o", "--output", dest="output",
                      help="Output file name. If not specified, output to stdout.")
    (options, args) = parser.parse_args()

    if len(args) != 1:
        usage()
        pass

    if options.follow is None:
        usage()
        pass

    if options.levels is None:
        usage()
        pass

    if options.exclude is None:
        options.exclude = []
        pass

    if options.output is None:
        out = sys.stdout
    else:
        out = open(options.output, "w")
        pass

    conn = sqlite3.connect(args[0])

    tries = []
    for follow in options.follow:
        if follow.startswith("+"):
            tree = create_callflow_tree(conn, follow[1:],
                                        options.levels,
                                        options.exclude,
                                        True)
        elif follow.startswith("-"):
            tree = create_callflow_tree(conn, follow[1:],
                                        options.levels,
                                        options.exclude,
                                        False)
        else:
            usage()
            pass
        tries.append(tree)
        pass

    out.write("digraph callflow {\n")
    for tree in tries:
        tree.draw(out)
        pass
    out.write("}\n")
    pass

if __name__ == "__main__":
    main()
    pass

